# Example secrets file - rename to secrets.toml and update values for local development
# For Streamlit Cloud deployment, copy these values to the Streamlit dashboard

# Google Drive file ID for the large feature selector model
# This is the ID portion from your Google Drive share link
# Example: For https://drive.google.com/file/d/1abCdEfGhIjKlMnOpQrStUvWxYz/view
# You would enter: SELECTOR_GDRIVE_URL = "1abCdEfGhIjKlMnOpQrStUvWxYz"
SELECTOR_GDRIVE_URL = "1A9RK40Z93DOcdCXnl7KKidFbNOJOyaeo"

# Optional: Add any other secrets your app needs
# DB_USERNAME = "username"
# DB_PASSWORD = "password"